theme: jekyll-theme-minimal
title: A11y-Live Homepage
description: A comprehensive, real-time accessibility testing tool that monitors DOM changes and provides instant feedback on WCAG compliance violations.
